export const AutoGeneratedMessage = (action) => {
  let message = "";
  switch (action) {
    case "emailExists":
      message = "📧 Email already registered. Proceeding with the next steps.";
      break;
    case "action2":
      message = "Message for action 2";
      break;
    case "action3":
      message = "Message for action 3";
      break;
    default:
      message = "Default message for unknown action";
      break;
  }
  return message;
};
