export const AutoGeneratedMessage = (action) => {
  let message = "";
  switch (action) {
    case "emailExists":
      message =
        "📧 We have your email on file. Connecting you now. Please wait";
      break;
    case "action2":
      message = "Message for action 2";
      break;
    case "action3":
      message = "Message for action 3";
      break;
    default:
      message = "Default message for unknown action";
      break;
  }
  return message;
};
